version: '2'

services:
  blog:
    build: php7
    volumes:
      - ../config/php/reporting.ini:/usr/local/etc/php/conf.d/reporting.ini
      - ../config/blog/virtualhost.conf:/etc/apache2/sites-available/000-default.conf
    networks:
      - front
      - back

  haproxy:
    image: haproxy:1.7.9-alpine
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "80:80"
    networks:
      - front
    depends_on:
      - blog

volumes:
  storage:
    driver: local

networks:
  front:
    driver: bridge
  back:
    driver: bridge