version: '2'

services:
  blog:
    build: php7
    volumes:
      - ../config/php/reporting.ini:/usr/local/etc/php/conf.d/reporting.ini
      - ../config/blog/virtualhost.conf:/etc/apache2/sites-available/000-default.conf
    networks:
      - front
      - back

  aella:
    image: tomcat:9-jre8-alpine
    ports:
      - "8080:8080"
    volumes:
      - /home/celine/ProCeline/workbox/code/aella/target/AellaExample.war:/usr/local/tomcat/webapps/ROOT.war

  aella-code:
    image: maven:3.5.2-jdk-8
    working_dir: /usr/src/
    command: mvn package

  haproxy:
    image: haproxy:1.7.9-alpine
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "80:80"
    networks:
      - front
    depends_on:
      - blog
      - aella

volumes:
  storage:
    driver: local
  aella-target:
    driver: local

networks:
  front:
    driver: bridge
  back:
    driver: bridge